### ISSUE TITLE
TODO: 接入更多的GUI控件

### ISSUE THREAD

**Issue by blueloveTH** [blueloveTH/PainterEngine#6]
- [ ] [多选框(checkbox)](https://www.painterengine.com/main/tutorials/lesson6/checkbox.htm)
- [x] [文本编辑框(edit)](https://www.painterengine.com/main/tutorials/lesson6/edit.htm)
- [ ] [资源浏览器(expolrer)](https://www.painterengine.com/main/tutorials/lesson6/explorer.htm)
- [x] [图片框(image)](https://www.painterengine.com/main/tutorials/lesson6/image.htm)
- [x] [静态文本框(label)](https://www.painterengine.com/main/tutorials/lesson6/label.htm)
- [ ] [列表框(list)](https://www.painterengine.com/main/tutorials/lesson6/list.htm)
- [ ] [菜单(menu)](https://www.painterengine.com/main/tutorials/lesson6/menu.htm)
- [ ] [消息框(messagebox)](https://www.painterengine.com/main/tutorials/lesson6/messagebox.htm)
- [x] [进度条(processbar)](https://www.painterengine.com/main/tutorials/lesson6/processbar.htm)
- [x] [按钮(pushbutton)](https://www.painterengine.com/main/tutorials/lesson6/pushbutton.htm)
- [ ] [单选框(radiobox)](https://www.painterengine.com/main/tutorials/lesson6/radiobox.htm)
- [ ] [下拉选择框(selectbar)](https://www.painterengine.com/main/tutorials/lesson6/selectbar.htm)
- [x] [滑动条(sliderbar)](https://www.painterengine.com/main/tutorials/lesson6/sliderbar.htm)
- [ ] [虚拟键盘(virtualkeyboard)](https://www.painterengine.com/main/tutorials/lesson6/virtualkeyboard.htm)
- [ ] [子窗体(widget)](https://www.painterengine.com/main/tutorials/lesson6/widget.htm)
